<?php

namespace Database\Seeders;

use App\Models\Affiliate;
use Illuminate\Database\Seeder;

class AffiliateSeeder extends Seeder
{
    public function run(): void
    {
        $affiliates = [
            [
                'name'             => 'Writesonic',
                'url'              => 'https://writesonic.com?ref=neuralrift',
                'website'          => 'https://writesonic.com',
                'description'      => 'El escritor IA más completo para blogs y copywriting.',
                'commission'       => '30% recurrente de por vida',
                'commission_type'  => 'recurring',
                'commission_value' => 30,
                'cookie_duration'  => '30 días',
                'pros'             => ['Comisión de por vida', 'Interfaz intuitiva', 'Soporte en español'],
                'cons'             => ['Límite en plan gratuito'],
                'rating'           => 4.8,
                'category'         => 'Escritura IA',
                'badge'            => 'Lo uso diariamente',
                'featured'         => true,
            ],
            [
                'name'             => 'ElevenLabs',
                'url'              => 'https://elevenlabs.io?ref=neuralrift',
                'website'          => 'https://elevenlabs.io',
                'description'      => 'La mejor IA para generación de voz y audio realista.',
                'commission'       => '22% recurrente',
                'commission_type'  => 'recurring',
                'commission_value' => 22,
                'cookie_duration'  => '90 días',
                'pros'             => ['Cookie de 90 días', 'Nicho en explosión', 'Alta conversión'],
                'cons'             => ['Comisión menor que otros'],
                'rating'           => 4.7,
                'category'         => 'Audio IA',
                'badge'            => 'Partner Oficial',
                'featured'         => true,
            ],
            [
                'name'             => 'Hostinger',
                'url'              => 'https://hostinger.com?ref=neuralrift',
                'website'          => 'https://hostinger.com',
                'description'      => 'El hosting que uso para todos mis proyectos web.',
                'commission'       => 'Hasta 60% por venta',
                'commission_type'  => 'one_time',
                'commission_value' => 60,
                'cookie_duration'  => '30 días',
                'pros'             => ['Comisión altísima', 'Conversión excelente', 'Marca conocida'],
                'cons'             => ['Pago único, no recurrente'],
                'rating'           => 4.6,
                'category'         => 'Hosting',
                'badge'            => 'Lo uso diariamente',
                'featured'         => true,
            ],
            [
                'name'             => 'Copy.ai',
                'url'              => 'https://copy.ai?ref=neuralrift',
                'website'          => 'https://copy.ai',
                'description'      => 'IA de copywriting para marketing y ventas.',
                'commission'       => '45% primer año',
                'commission_type'  => 'recurring',
                'commission_value' => 45,
                'cookie_duration'  => '60 días',
                'pros'             => ['45% — una de las más altas', 'Cookie de 60 días'],
                'cons'             => ['Solo primer año'],
                'rating'           => 4.5,
                'category'         => 'Escritura IA',
                'badge'            => null,
                'featured'         => false,
            ],
            [
                'name'             => 'NeuronWriter',
                'url'              => 'https://neuronwriter.com?ref=neuralrift',
                'website'          => 'https://neuronwriter.com',
                'description'      => 'SEO + IA: la herramienta definitiva para rankear en Google.',
                'commission'       => '30% de por vida',
                'commission_type'  => 'recurring',
                'commission_value' => 30,
                'cookie_duration'  => '60 días',
                'pros'             => ['Comisión lifetime', 'Nicho SEO muy rentable'],
                'cons'             => ['Menos conocida que competidores'],
                'rating'           => 4.6,
                'category'         => 'SEO IA',
                'badge'            => 'Partner Oficial',
                'featured'         => true,
            ],
            [
                'name'             => 'DigitalOcean',
                'url'              => 'https://m.do.co/c/TUREFCODE',
                'website'          => 'https://digitalocean.com',
                'description'      => 'Cloud hosting para developers. El mejor VPS para proyectos Laravel y Node.',
                'commission'       => '$200 USD por referido calificado',
                'commission_type'  => 'one_time',
                'commission_value' => 200,
                'cookie_duration'  => '90 días',
                'pros'             => ['Comisión altísima', 'Marca muy reconocida', 'Cookie de 90 días'],
                'cons'             => ['Pago único, no recurrente', 'El referido debe gastar $25+'],
                'rating'           => 4.8,
                'category'         => 'Cloud / Hosting',
                'badge'            => 'Lo uso en producción',
                'featured'         => true,
                'active'           => true,
            ],
            [
                'name'             => 'Make.com',
                'url'              => 'https://make.com?ref=TUREFCODE',
                'website'          => 'https://make.com',
                'description'      => 'La mejor plataforma de automatización visual. Conéctalo todo con IA.',
                'commission'       => '20% recurrente',
                'commission_type'  => 'recurring',
                'commission_value' => 20,
                'cookie_duration'  => '30 días',
                'pros'             => ['Comisión recurrente', 'Producto con alta retención', 'Muy popular en LATAM'],
                'cons'             => ['Competencia alta con Zapier'],
                'rating'           => 4.7,
                'category'         => 'Automatización',
                'badge'            => 'Partner Oficial',
                'featured'         => true,
                'active'           => true,
            ],
            [
                'name'             => 'Surfer SEO',
                'url'              => 'https://surferseo.com?ref=TUREFCODE',
                'website'          => 'https://surferseo.com',
                'description'      => 'La herramienta de SEO con IA que uso para optimizar cada artículo de NeuralRift.',
                'commission'       => '25% recurrente',
                'commission_type'  => 'recurring',
                'commission_value' => 25,
                'cookie_duration'  => '60 días',
                'pros'             => ['Comisión recurrente', 'Nicho SEO muy rentable', 'Alta conversión'],
                'cons'             => ['Precio alto puede frenar conversión'],
                'rating'           => 4.6,
                'category'         => 'SEO',
                'badge'            => 'Lo uso diariamente',
                'featured'         => false,
                'active'           => true,
            ],
            [
                'name'             => 'Wise',
                'url'              => 'https://wise.com/invite/TUREFCODE',
                'website'          => 'https://wise.com',
                'description'      => 'La forma más barata de recibir dólares desde Colombia y LATAM como freelancer.',
                'commission'       => 'Bonus por referido activo',
                'commission_type'  => 'one_time',
                'commission_value' => 50,
                'cookie_duration'  => '30 días',
                'pros'             => ['Muy relevante para audiencia LATAM', 'Alta conversión', 'Producto que la gente necesita'],
                'cons'             => ['Comisión variable según país'],
                'rating'           => 4.9,
                'category'         => 'Finanzas',
                'badge'            => 'Lo uso personalmente',
                'featured'         => true,
                'active'           => true,
            ],
        ];

        foreach ($affiliates as $aff) {
            Affiliate::create($aff);
        }
    }
}
