<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        $tools = [

            // ── Chatbots & Asistentes ────────────────────────────────────────
            [
                'name' => 'ChatGPT',
                'url' => 'https://chat.openai.com',
                'website' => 'https://openai.com',
                'description' => 'El asistente de IA más popular del mundo. GPT-4o responde preguntas, redacta textos, analiza imágenes, genera código y mucho más. Imprescindible para cualquier persona que trabaje con IA.',
                'description_en' => 'The most popular AI assistant in the world. GPT-4o answers questions, writes text, analyzes images, generates code and much more.',
                'category' => 'Chatbots & Asistentes',
                'badge' => 'Esencial',
                'rating' => 4.8,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Modelo GPT-4o incluido en plan gratuito', 'Multimodal: texto, imágenes, voz y código', 'Plugins y GPTs personalizados', 'API robusta para developers'],
                'cons' => ['Límites de mensajes en plan gratuito', 'Sin acceso a internet en tiempo real (sin plugins)', 'Puede alucinar en datos recientes'],
                'featured' => true,
                'order' => 1,
            ],
            [
                'name' => 'Claude (Anthropic)',
                'url' => 'https://claude.ai',
                'website' => 'https://anthropic.com',
                'description' => 'El modelo de IA de Anthropic, conocido por sus respuestas largas y precisas, excelente razonamiento y un contexto de hasta 200K tokens. Ideal para analizar documentos largos, código complejo y tareas de escritura avanzada.',
                'description_en' => 'Anthropic\'s AI model, known for long and accurate responses, excellent reasoning and up to 200K token context window.',
                'category' => 'Chatbots & Asistentes',
                'badge' => 'Top Calidad',
                'rating' => 4.9,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Contexto de 200K tokens (documentos completos)', 'Razonamiento superior en tareas complejas', 'Muy preciso y honesto sobre sus limitaciones', 'Claude.ai gratuito con acceso a modelos recientes'],
                'cons' => ['Sin acceso a internet en tiempo real', 'Límites de uso en el plan gratuito', 'Sin generación de imágenes nativa'],
                'featured' => true,
                'order' => 2,
            ],
            [
                'name' => 'Perplexity AI',
                'url' => 'https://perplexity.ai',
                'website' => 'https://perplexity.ai',
                'description' => 'Motor de búsqueda potenciado por IA que cita sus fuentes en tiempo real. Reemplaza a Google para investigación: obtén respuestas precisas con referencias verificables, sin pasar por 10 páginas de resultados.',
                'description_en' => 'AI-powered search engine that cites its sources in real time. Replaces Google for research with accurate, verifiable answers.',
                'category' => 'Chatbots & Asistentes',
                'badge' => 'Recomendado',
                'rating' => 4.7,
                'commission' => '20% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 20,
                'cookie_duration' => '90 días',
                'pros' => ['Respuestas con fuentes citadas y verificables', 'Acceso a internet en tiempo real', 'Plan gratuito generoso', 'Modo Pro con GPT-4 y Claude'],
                'cons' => ['Respuestas más cortas que ChatGPT para redacción', 'Menos capacidades de generación creativa', 'Pro cuesta $20/mes'],
                'featured' => true,
                'order' => 3,
            ],

            // ── Escritura & Contenido ────────────────────────────────────────
            [
                'name' => 'Jasper',
                'url' => 'https://jasper.ai',
                'website' => 'https://jasper.ai',
                'description' => 'La herramienta de escritura IA líder para equipos de marketing. Genera artículos SEO, emails, anuncios y posts para redes sociales con el tono de tu marca. Integración nativa con SurferSEO.',
                'description_en' => 'The leading AI writing tool for marketing teams. Generate SEO articles, emails, ads and social posts with your brand voice.',
                'category' => 'Escritura IA',
                'badge' => 'Popular',
                'rating' => 4.5,
                'commission' => '30% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 30,
                'cookie_duration' => '30 días',
                'pros' => ['Plantillas para más de 50 tipos de contenido', 'Brand voice para mantener consistencia', 'Integración con SurferSEO', 'Soporte para 30+ idiomas'],
                'cons' => ['Precio elevado ($49-$125/mes)', 'Curva de aprendizaje inicial', 'Requiere revisión humana para textos técnicos'],
                'featured' => false,
                'order' => 4,
            ],
            [
                'name' => 'Copy.ai',
                'url' => 'https://copy.ai',
                'website' => 'https://copy.ai',
                'description' => 'Plataforma de escritura IA con flujos de trabajo automatizados para equipos de ventas y marketing. Su plan gratuito es uno de los más generosos del mercado: 2.000 palabras al mes sin tarjeta.',
                'description_en' => 'AI writing platform with automated workflows for sales and marketing teams. Has one of the most generous free plans in the market.',
                'category' => 'Escritura IA',
                'badge' => 'Freemium',
                'rating' => 4.3,
                'commission' => '45% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 45,
                'cookie_duration' => '60 días',
                'pros' => ['Plan gratuito sin tarjeta de crédito', 'Flujos de trabajo (workflows) para pipelines de ventas', 'Más de 90 plantillas', 'Chat IA con acceso a internet'],
                'cons' => ['Limitado en planes gratuitos', 'Outputs más genéricos que Jasper', 'Sin integración nativa de SEO'],
                'featured' => false,
                'order' => 5,
            ],

            // ── Generación de Imágenes ───────────────────────────────────────
            [
                'name' => 'Midjourney',
                'url' => 'https://midjourney.com',
                'website' => 'https://midjourney.com',
                'description' => 'El generador de imágenes IA con el mejor sentido artístico del mercado. Produce imágenes fotorrealistas, ilustraciones y concept art de calidad profesional. Funciona vía Discord y su propia web.',
                'description_en' => 'The AI image generator with the best artistic sense on the market. Produces photorealistic images and professional-quality concept art.',
                'category' => 'Generación de Imágenes',
                'badge' => 'Mejor Calidad',
                'rating' => 4.8,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Calidad artística superior a la competencia', 'Excelente para concept art y fotografía creativa', 'Comunidad activa en Discord', 'Actualizaciones frecuentes del modelo'],
                'cons' => ['Sin plan gratuito (desde $10/mes)', 'Interfaz via Discord es poco intuitiva', 'Sin API pública para developers'],
                'featured' => true,
                'order' => 6,
            ],
            [
                'name' => 'Leonardo.ai',
                'url' => 'https://leonardo.ai',
                'website' => 'https://leonardo.ai',
                'description' => 'Generador de imágenes IA con plan gratuito generoso (150 créditos/día). Especializado en videojuegos, concept art y personajes consistentes. Incluye herramientas de motion y canvas interactivo.',
                'description_en' => 'AI image generator with a generous free plan. Specialized in game assets, concept art and consistent characters.',
                'category' => 'Generación de Imágenes',
                'badge' => 'Gratis para empezar',
                'rating' => 4.5,
                'commission' => '25% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 25,
                'cookie_duration' => '30 días',
                'pros' => ['150 créditos gratuitos al día', 'Especializado en personajes y game assets', 'Canvas interactivo para edición', 'Modelos fine-tuneados por la comunidad'],
                'cons' => ['Calidad ligeramente inferior a Midjourney', 'Interfaz puede ser abrumadora al inicio', 'Límites de uso en plan gratuito'],
                'featured' => false,
                'order' => 7,
            ],
            [
                'name' => 'DALL·E 3',
                'url' => 'https://openai.com/dall-e-3',
                'website' => 'https://openai.com',
                'description' => 'El generador de imágenes de OpenAI, integrado directamente en ChatGPT Plus. Destaca por su capacidad de seguir instrucciones textuales complejas con precisión. Ideal para ilustraciones con texto dentro de la imagen.',
                'description_en' => 'OpenAI\'s image generator, integrated directly into ChatGPT Plus. Excellent at following complex text instructions accurately.',
                'category' => 'Generación de Imágenes',
                'badge' => 'Incluido en ChatGPT',
                'rating' => 4.4,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Incluido en ChatGPT Plus ($20/mes)', 'Excelente con instrucciones complejas y texto en imágenes', 'Políticas de seguridad claras', 'Sin conocimiento técnico de prompts requerido'],
                'cons' => ['Requiere suscripción ChatGPT Plus', 'Menos control artístico que Midjourney', 'Sin API de imágenes en plan básico'],
                'featured' => false,
                'order' => 8,
            ],

            // ── Video IA ─────────────────────────────────────────────────────
            [
                'name' => 'Runway',
                'url' => 'https://runwayml.com',
                'website' => 'https://runwayml.com',
                'description' => 'La plataforma de video IA más avanzada para creadores. Gen-3 Alpha genera videos de 5-10 segundos de altísima calidad a partir de texto o imagen. Usada por estudios de cine y agencias creativas.',
                'description_en' => 'The most advanced AI video platform for creators. Gen-3 Alpha generates high-quality 5-10 second videos from text or images.',
                'category' => 'Video IA',
                'badge' => 'Líder en Video',
                'rating' => 4.6,
                'commission' => '20% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 20,
                'cookie_duration' => '30 días',
                'pros' => ['Calidad de video superior (Gen-3 Alpha)', 'Suite completa de edición de video IA', 'Herramientas de rotoscopia y efectos avanzados', 'Plan gratuito con 125 créditos'],
                'cons' => ['Créditos se consumen rápido', 'Plan Pro desde $15/mes', 'Requiere GPU potente para procesar localmente'],
                'featured' => true,
                'order' => 9,
            ],
            [
                'name' => 'HeyGen',
                'url' => 'https://heygen.com',
                'website' => 'https://heygen.com',
                'description' => 'Crea videos con avatares IA realistas sin grabar nada. Ideal para videos de producto, formación corporativa y contenido de redes sociales. Soporta clonación de voz y traducción automática a más de 40 idiomas.',
                'description_en' => 'Create realistic AI avatar videos without recording anything. Perfect for product videos, corporate training and social media content.',
                'category' => 'Video IA',
                'badge' => 'Recomendado',
                'rating' => 4.5,
                'commission' => '30% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 30,
                'cookie_duration' => '30 días',
                'pros' => ['Avatares hiperrealistas en minutos', 'Traducción y doblaje automático a 40+ idiomas', 'Clonación de voz instantánea', 'Excelente para escalar contenido en múltiples idiomas'],
                'cons' => ['Plan gratuito muy limitado (1 minuto/mes)', 'Planes desde $29/mes', 'Los avatares custom requieren plan Enterprise'],
                'featured' => false,
                'order' => 10,
            ],
            [
                'name' => 'InVideo AI',
                'url' => 'https://invideo.io',
                'website' => 'https://invideo.io',
                'description' => 'Genera videos completos desde un prompt de texto. Escribe "quiero un video sobre los 5 mejores modelos de IA" y obtienes un video listo con voz en off, imágenes y subtítulos. El mejor ratio calidad-precio para contenido en volumen.',
                'description_en' => 'Generate complete videos from a text prompt. Write your idea and get a ready-to-publish video with voiceover, images and subtitles.',
                'category' => 'Video IA',
                'badge' => 'Mejor Precio',
                'rating' => 4.3,
                'commission' => '50% primer mes',
                'commission_type' => 'one_time',
                'commission_value' => 50,
                'cookie_duration' => '60 días',
                'pros' => ['Genera videos completos desde texto', 'Biblioteca de 16M+ clips y música sin copyright', 'Voz en off en múltiples idiomas', 'Desde $25/mes con exportación ilimitada'],
                'cons' => ['Calidad inferior a Runway para efectos avanzados', 'Videos con cierto aspecto "automático"', 'Edición manual limitada'],
                'featured' => false,
                'order' => 11,
            ],

            // ── Código IA ────────────────────────────────────────────────────
            [
                'name' => 'GitHub Copilot',
                'url' => 'https://github.com/features/copilot',
                'website' => 'https://github.com',
                'description' => 'El asistente de código IA más usado en el mundo, integrado en VS Code, JetBrains, Neovim y más. Autocompleta funciones enteras, sugiere tests y explica código legado. Desde GitHub, el hogar de 100M+ developers.',
                'description_en' => 'The most widely used AI coding assistant, integrated into VS Code, JetBrains and more. Completes entire functions and suggests tests.',
                'category' => 'Código IA',
                'badge' => 'Estándar de la industria',
                'rating' => 4.6,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Integración nativa en todos los IDEs populares', 'Gratis para estudiantes y proyectos open source', 'Copilot Chat para explicar y refactorizar código', 'Entrenado en miles de millones de líneas de código real'],
                'cons' => ['$10/mes para uso individual', 'Puede sugerir código inseguro u obsoleto', 'Requiere revisión humana siempre'],
                'featured' => true,
                'order' => 12,
            ],
            [
                'name' => 'Cursor',
                'url' => 'https://cursor.sh',
                'website' => 'https://cursor.sh',
                'description' => 'El editor de código IA que está reemplazando a VS Code entre developers avanzados. Cursor entiende todo tu codebase, no solo el archivo abierto. Puedes pedirle que edite múltiples archivos a la vez con lenguaje natural.',
                'description_en' => 'The AI code editor replacing VS Code for advanced developers. Understands your entire codebase and edits multiple files at once.',
                'category' => 'Código IA',
                'badge' => 'Tendencia 2025',
                'rating' => 4.8,
                'commission' => '20% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 20,
                'cookie_duration' => '30 días',
                'pros' => ['Entiende el contexto completo del proyecto', 'Edición multi-archivo con instrucciones en lenguaje natural', 'Usa GPT-4, Claude y modelos propios', 'Plan gratuito con 2.000 completions/mes'],
                'cons' => ['Pro cuesta $20/mes', 'Curva de adaptación si vienes de VS Code', 'Consume bastante RAM en proyectos grandes'],
                'featured' => true,
                'order' => 13,
            ],

            // ── Automatización ───────────────────────────────────────────────
            [
                'name' => 'Make (ex-Integromat)',
                'url' => 'https://make.com',
                'website' => 'https://make.com',
                'description' => 'La alternativa visual a Zapier con mucho más poder y mejor precio. Conecta más de 1.500 apps con flujos visuales estilo diagrama. Ideal para automatizar procesos de negocio complejos con lógica condicional avanzada.',
                'description_en' => 'The visual Zapier alternative with much more power and better pricing. Connect 1,500+ apps with visual diagram-style flows.',
                'category' => 'Automatización',
                'badge' => 'Mejor Precio',
                'rating' => 4.7,
                'commission' => '20% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 20,
                'cookie_duration' => '30 días',
                'pros' => ['Plan gratuito con 1.000 operaciones/mes', 'Interfaz visual muy potente', 'Precio muy competitivo vs Zapier', 'Soporte para lógica compleja y bucles'],
                'cons' => ['Curva de aprendizaje más alta que Zapier', 'Documentación mejorable en español', 'Soporte más lento que competidores premium'],
                'featured' => false,
                'order' => 14,
            ],
            [
                'name' => 'n8n',
                'url' => 'https://n8n.io',
                'website' => 'https://n8n.io',
                'description' => 'La herramienta de automatización open source favorita de los desarrolladores. Se puede auto-hospedar gratis o usar la nube. Permite escribir código JavaScript en cualquier nodo. Perfecta para automatizaciones con IA a medida.',
                'description_en' => 'The open-source automation tool loved by developers. Self-hostable for free, with JavaScript coding in any node and full AI integration.',
                'category' => 'Automatización',
                'badge' => 'Open Source',
                'rating' => 4.6,
                'commission' => '20% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 20,
                'cookie_duration' => '30 días',
                'pros' => ['100% open source, auto-hosteable', 'Código JavaScript en cualquier nodo', 'Nodos nativos de IA (OpenAI, LangChain, etc.)', 'Sin límite de ejecuciones al auto-hospedar'],
                'cons' => ['Requiere conocimientos técnicos para el self-hosting', 'Cloud desde $24/mes', 'Menos integraciones nativas que Zapier/Make'],
                'featured' => false,
                'order' => 15,
            ],
            [
                'name' => 'Zapier',
                'url' => 'https://zapier.com',
                'website' => 'https://zapier.com',
                'description' => 'El líder de la automatización sin código. Conecta más de 7.000 aplicaciones sin saber programar. Su nueva capa de IA permite crear Zaps con lenguaje natural y usar agentes IA en tus flujos de trabajo.',
                'description_en' => 'The no-code automation leader. Connect 7,000+ apps without coding. AI layer lets you create Zaps in natural language.',
                'category' => 'Automatización',
                'badge' => 'Más Popular',
                'rating' => 4.4,
                'commission' => '20-30% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 25,
                'cookie_duration' => '30 días',
                'pros' => ['7.000+ integraciones (más que nadie)', 'Extremadamente fácil de usar sin código', 'Agentes IA nativos en flujos', 'Soporte de calidad y documentación excelente'],
                'cons' => ['El más caro del mercado (desde $20/mes en planes limitados)', 'Plan gratuito solo 100 tareas/mes', 'Menos flexible que Make para lógica compleja'],
                'featured' => false,
                'order' => 16,
            ],

            // ── SEO & Marketing ──────────────────────────────────────────────
            [
                'name' => 'Surfer SEO',
                'url' => 'https://surferseo.com',
                'website' => 'https://surferseo.com',
                'description' => 'La herramienta SEO impulsada por IA para escribir artículos que rankean en Google. Analiza los 10 primeros resultados para tu keyword y te da una guía exacta de palabras, estructura y longitud óptima.',
                'description_en' => 'AI-powered SEO tool to write articles that rank on Google. Analyzes top 10 results and gives you exact guidance on words and structure.',
                'category' => 'SEO & Marketing',
                'badge' => 'Recomendado',
                'rating' => 4.6,
                'commission' => '25% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 25,
                'cookie_duration' => '30 días',
                'pros' => ['Content Score en tiempo real mientras escribes', 'Integración con Google Docs y WordPress', 'Keyword research y clustering IA', 'Auditoría de páginas existentes'],
                'cons' => ['Desde $89/mes (caro para freelancers)', 'El Content Score no garantiza posicionamiento', 'Limitado a artículos, no otras páginas'],
                'featured' => false,
                'order' => 17,
            ],
            [
                'name' => 'Semrush',
                'url' => 'https://semrush.com',
                'website' => 'https://semrush.com',
                'description' => 'La suite de marketing digital más completa del mercado. SEO, SEM, content marketing, social media y PR en una sola herramienta. Su módulo de IA analiza a tu competencia y sugiere el contenido exacto que deberías crear.',
                'description_en' => 'The most complete digital marketing suite. SEO, SEM, content marketing, social media and PR in a single tool.',
                'category' => 'SEO & Marketing',
                'badge' => 'Suite Completa',
                'rating' => 4.7,
                'commission' => '$200 por venta + $10 por trial',
                'commission_type' => 'one_time',
                'commission_value' => 200,
                'cookie_duration' => '120 días',
                'pros' => ['La base de datos de keywords más grande (25B+ palabras)', 'Análisis de competencia muy detallado', 'Suite completa para todos los canales de marketing', 'Prueba gratuita de 7 días'],
                'cons' => ['Precio elevado (desde $130/mes)', 'Curva de aprendizaje significativa', 'Puede ser excesivo para proyectos pequeños'],
                'featured' => false,
                'order' => 18,
            ],

            // ── Voz & Audio ──────────────────────────────────────────────────
            [
                'name' => 'ElevenLabs',
                'url' => 'https://elevenlabs.io',
                'website' => 'https://elevenlabs.io',
                'description' => 'La síntesis de voz IA más realista del mercado. Clona tu voz en minutos con solo 1 minuto de audio, genera narraciones en 29 idiomas y crea efectos de sonido. El estándar para podcasters, creadores y apps de voz.',
                'description_en' => 'The most realistic AI voice synthesis on the market. Clone your voice in minutes, generate narrations in 29 languages and create sound effects.',
                'category' => 'Voz & Audio',
                'badge' => 'Líder en Voz',
                'rating' => 4.8,
                'commission' => '22% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 22,
                'cookie_duration' => '30 días',
                'pros' => ['Calidad de voz prácticamente indistinguible de humanos', 'Clonación de voz con solo 1 minuto de audio', 'API robusta con baja latencia para apps', 'Plan gratuito con 10.000 caracteres/mes'],
                'cons' => ['El plan gratuito es muy limitado para uso profesional', 'Preocupaciones éticas sobre uso indebido de voces', 'Precio escala rápido en volumen alto'],
                'featured' => true,
                'order' => 19,
            ],
            [
                'name' => 'Suno',
                'url' => 'https://suno.com',
                'website' => 'https://suno.com',
                'description' => 'Genera canciones completas —con letra, melodía y producción— desde un prompt de texto. Suno v4 produce música de calidad profesional en cualquier género en menos de 30 segundos. El fenómeno musical de la IA generativa.',
                'description_en' => 'Generate complete songs — with lyrics, melody and production — from a text prompt. Suno v4 produces professional-quality music in any genre.',
                'category' => 'Voz & Audio',
                'badge' => 'Tendencia',
                'rating' => 4.5,
                'commission' => '25% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 25,
                'cookie_duration' => '30 días',
                'pros' => ['Canciones completas con letra y producción desde texto', 'Calidad musical sorprendente', '50 créditos gratuitos al día', 'Cualquier género musical imaginable'],
                'cons' => ['Derechos de autor poco claros en uso comercial', 'Sin control granular sobre la instrumentación', 'Plan Pro necesario para descargas comerciales'],
                'featured' => false,
                'order' => 20,
            ],

            // ── Productividad ─────────────────────────────────────────────────
            [
                'name' => 'Notion AI',
                'url' => 'https://notion.so',
                'website' => 'https://notion.so',
                'description' => 'El workspace todo-en-uno con IA integrada. Redacta, resume, traduce y organiza tu conocimiento dentro de la misma herramienta donde trabajas. Notion AI se activa con un atajo de teclado en cualquier documento.',
                'description_en' => 'The all-in-one workspace with built-in AI. Write, summarize, translate and organize your knowledge — all within the same tool.',
                'category' => 'Productividad',
                'badge' => 'Todo en uno',
                'rating' => 4.5,
                'commission' => '50% primer año',
                'commission_type' => 'recurring',
                'commission_value' => 50,
                'cookie_duration' => '90 días',
                'pros' => ['IA integrada en el workspace donde ya trabajas', 'Base de datos, wikis, proyectos y docs en un lugar', 'Q&A sobre tus propios documentos', 'Plan gratuito disponible'],
                'cons' => ['La IA cuesta $10/mes adicional', 'Puede volverse lento en workspaces muy grandes', 'Curva de aprendizaje para nuevos usuarios'],
                'featured' => false,
                'order' => 21,
            ],
            [
                'name' => 'Otter.ai',
                'url' => 'https://otter.ai',
                'website' => 'https://otter.ai',
                'description' => 'Transcripción automática de reuniones con IA. Se integra con Zoom, Google Meet y Teams para tomar notas, generar resúmenes y responder preguntas sobre lo discutido. Ideal para equipos remotos y periodistas.',
                'description_en' => 'Automatic AI meeting transcription. Integrates with Zoom, Meet and Teams to take notes, generate summaries and answer questions.',
                'category' => 'Productividad',
                'badge' => 'Reuniones',
                'rating' => 4.4,
                'commission' => '20% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 20,
                'cookie_duration' => '30 días',
                'pros' => ['Integración nativa con Zoom, Meet y Teams', '300 minutos gratuitos al mes', 'Resúmenes automáticos y action items', 'Chat sobre la transcripción para buscar info'],
                'cons' => ['Precisión menor con acentos fuertes o ruido', 'Solo en inglés nativo (otros idiomas en beta)', 'Plan Pro necesario para reuniones largas'],
                'featured' => false,
                'order' => 22,
            ],

            // ── Diseño IA ─────────────────────────────────────────────────────
            [
                'name' => 'Canva AI',
                'url' => 'https://canva.com',
                'website' => 'https://canva.com',
                'description' => 'La herramienta de diseño más usada en el mundo ahora con IA integrada. Magic Studio genera imágenes, elimina fondos, amplía fotos, crea presentaciones desde texto y mucho más. El diseño IA más accesible del mercado.',
                'description_en' => 'The world\'s most-used design tool now with built-in AI. Magic Studio generates images, removes backgrounds, creates presentations from text and more.',
                'category' => 'Diseño IA',
                'badge' => 'Más Accesible',
                'rating' => 4.6,
                'commission' => '25% por nueva suscripción Pro',
                'commission_type' => 'one_time',
                'commission_value' => 25,
                'cookie_duration' => '30 días',
                'pros' => ['Plan gratuito muy completo', 'Magic Studio: texto-a-imagen, fondo eliminado, etc.', 'Millones de plantillas para todo tipo de diseño', 'Sin curva de aprendizaje'],
                'cons' => ['Las herramientas IA más avanzadas requieren Pro ($13/mes)', 'Menos control que Adobe para diseño profesional', 'Las imágenes generadas tienen calidad variable'],
                'featured' => false,
                'order' => 23,
            ],

            // ── Agentes & LLMs Avanzados ─────────────────────────────────────
            [
                'name' => 'Gemini Advanced',
                'url' => 'https://gemini.google.com',
                'website' => 'https://gemini.google.com',
                'description' => 'El asistente IA de Google con acceso a búsqueda en tiempo real e integración nativa con Gmail, Docs, Drive y YouTube. Gemini 1.5 Pro tiene contexto de 1 millón de tokens — el mayor del mercado.',
                'description_en' => 'Google\'s AI assistant with real-time search and native integration with Gmail, Docs, Drive and YouTube. 1M token context window.',
                'category' => 'Chatbots & Asistentes',
                'badge' => 'Google',
                'rating' => 4.4,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Integración perfecta con todo el ecosistema Google', 'Acceso a internet en tiempo real', '1 millón de tokens de contexto (Gemini 1.5 Pro)', 'Incluido en Google One AI Premium ($20/mes)'],
                'cons' => ['Rezagado frente a GPT-4 y Claude en razonamiento complejo', 'Preocupaciones de privacidad al usar con Google Workspace', 'Sin programa de afiliados'],
                'featured' => false,
                'order' => 24,
            ],
            [
                'name' => 'Grok (xAI)',
                'url' => 'https://x.ai/grok',
                'website' => 'https://x.ai',
                'description' => 'El modelo IA de Elon Musk integrado en X (Twitter). Accede a publicaciones de X en tiempo real, tiene menos filtros de contenido que sus competidores y su versión Grok-2 compite directamente con GPT-4. Incluido en X Premium+.',
                'description_en' => 'Elon Musk\'s AI model integrated into X (Twitter). Real-time X posts access, fewer content filters, and Grok-2 competes with GPT-4.',
                'category' => 'Chatbots & Asistentes',
                'badge' => 'Nuevo',
                'rating' => 4.2,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Acceso a datos de X en tiempo real', 'Menos restricciones de contenido', 'API gratuita con límites generosos', 'Integrado en la red social más usada por la industria tech'],
                'cons' => ['Requiere X Premium+ ($16/mes) para acceso completo', 'Menos preciso que GPT-4 y Claude en benchmarks', 'Ecosistema de plugins limitado'],
                'featured' => false,
                'order' => 25,
            ],
            [
                'name' => 'Descript',
                'url' => 'https://descript.com',
                'website' => 'https://descript.com',
                'description' => 'Edita audio y video editando el texto de la transcripción. Descript convierte grabaciones en texto y luego puedes cortar, mover o eliminar partes simplemente borrando palabras. Incluye Overdub para clonar tu voz y corregir errores.',
                'description_en' => 'Edit audio and video by editing the transcript text. Cut, move or remove parts by deleting words. Includes voice cloning for corrections.',
                'category' => 'Video IA',
                'badge' => 'Innovador',
                'rating' => 4.5,
                'commission' => '15% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 15,
                'cookie_duration' => '30 días',
                'pros' => ['Paradigma único: edita video editando texto', 'Overdub para clonar voz y corregir grabaciones', 'Ideal para podcasters y creadores de video', 'Colaboración en tiempo real'],
                'cons' => ['Curva de aprendizaje diferente a editores tradicionales', 'Pro desde $24/mes', 'Limitado para edición de video avanzada/cinematográfica'],
                'featured' => false,
                'order' => 26,
            ],
            [
                'name' => 'Frase.io',
                'url' => 'https://frase.io',
                'website' => 'https://frase.io',
                'description' => 'Herramienta de contenido SEO que combina investigación, brief y escritura en un flujo de trabajo único. Analiza los mejores resultados de Google para tu keyword y genera un brief detallado antes de escribir el artículo.',
                'description_en' => 'SEO content tool combining research, brief creation and writing in one workflow. Analyzes top Google results before generating your article.',
                'category' => 'SEO & Marketing',
                'badge' => 'SEO',
                'rating' => 4.3,
                'commission' => '30% recurrente',
                'commission_type' => 'recurring',
                'commission_value' => 30,
                'cookie_duration' => '60 días',
                'pros' => ['Investigación + brief + escritura en un solo lugar', 'Precio competitivo (desde $15/mes)', 'Análisis de preguntas de "La gente también pregunta"', 'Score SEO en tiempo real'],
                'cons' => ['Interfaz menos pulida que SurferSEO', 'Escritor IA menos potente que Jasper', 'Base de datos de keywords más pequeña'],
                'featured' => false,
                'order' => 27,
            ],
            [
                'name' => 'Luma AI (Dream Machine)',
                'url' => 'https://lumalabs.ai/dream-machine',
                'website' => 'https://lumalabs.ai',
                'description' => 'Generador de video IA de Luma Labs con calidad cinematográfica. Dream Machine genera clips de 5 segundos con movimientos de cámara realistas, física creíble y coherencia visual excepcional. Competidor directo de Runway Gen-3.',
                'description_en' => 'Luma Labs\' cinematic AI video generator. Dream Machine creates 5-second clips with realistic camera movements and exceptional visual coherence.',
                'category' => 'Video IA',
                'badge' => 'Nuevo',
                'rating' => 4.5,
                'commission' => 'Sin programa de afiliados',
                'commission_type' => 'one_time',
                'commission_value' => 0,
                'cookie_duration' => null,
                'pros' => ['Calidad cinematográfica con física realista', '30 generaciones gratuitas al mes', 'Texto-a-video e imagen-a-video', 'Movimientos de cámara muy naturales'],
                'cons' => ['Sin programa de afiliados aún', 'Tiempos de espera en horas pico', 'Plan Pro ($30/mes) para uso profesional'],
                'featured' => false,
                'order' => 28,
            ],
        ];

        $now = now();

        foreach ($tools as $tool) {
            $slug = Str::slug($tool['name']);
            DB::table('affiliates')->updateOrInsert(
                ['slug' => $slug],
                array_merge($tool, [
                    'slug' => $slug,
                    'logo' => null,
                    'active' => true,
                    'clicks_count' => 0,
                    'pros' => json_encode($tool['pros']),
                    'cons' => json_encode($tool['cons']),
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }

    public function down(): void
    {
        $slugs = [
            'chatgpt', 'claude-anthropic', 'perplexity-ai', 'jasper', 'copy-ai',
            'midjourney', 'leonardoai', 'dalle-3', 'runway', 'heygen',
            'invideo-ai', 'github-copilot', 'cursor', 'make-ex-integromat',
            'n8n', 'zapier', 'surfer-seo', 'semrush', 'elevenlabs', 'suno',
            'notion-ai', 'otterai', 'canva-ai', 'gemini-advanced',
            'grok-xai', 'descript', 'fraseio', 'luma-ai-dream-machine',
        ];

        DB::table('affiliates')->whereIn('slug', $slugs)->delete();
    }
};
